pixi_hospital:
    resource: "@PixiHospitalBundle/Controller/"
    type:     annotation
    prefix:   /

pixi_loyalty_manager:
    resource: "@PixiLoyaltyManagerBundle/Controller/"
    type:     annotation
    prefix:   /

pixi_core:
    resource: "@PixiCoreBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout