pixi_iht:
    resource: "@PixiIHTBundle/Controller/"
    type:     annotation
    prefix:   /

pixi_core:
    resource: "@PixiCoreBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout