security:
    encoders:
        Pixi\CoreBundle\Entity\User:
          algorithm: plaintext

    providers:
        database_provider:
            entity:
                class: PixiCoreBundle:User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MANAGE_ROLE]
        ROLE_RECEPTION: ROLE_ADMIN
        ROLE_PHARMACY: ROLE_ADMIN
        ROLE_MANAGEMENT: [ROLE_RECEPTION, ROLE_PHARMACY, ROLE_SUPER_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|views)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            provider: database_provider
            logout:
                path: /logout
                target: /


    access_control:
        - {path: ^/admin/, roles: ROLE_ADMIN}
