security:
    encoders:
        Pixi\CoreBundle\Entity\User:
          algorithm: plaintext

    providers:
        database_provider:
            entity:
                class: PixiCoreBundle:User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MANAGE_ROLE]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            provider: database_provider
            logout:
                path: /logout
                target: /
