services:
  bundle_service:
    class: Pixi\CoreBundle\Services\BundleService
    arguments: [@event_dispatcher]
    calls:
      - [ setContainer,[ @service_container ] ]
    tags:
      - { name: kernel.event_listener, event: pixi.admin_routes, method: superAdminRoutes }

