services:
    kernel.listener.loyalty_manager_service:
        class: Pixi\IHTBundle\Services\IHTService
        arguments: [@event_dispatcher]
        tags:
            - { name: kernel.event_listener, event: pixi.admin_js_files, method: adminJsFiles }
            - { name: kernel.event_listener, event: pixi.admin_routes, method: adminRoutes }
            - { name: kernel.event_listener, event: pixi.admin_sidebar_entries, method: adminSidebar }