services:
    hms_service:
          class: Pixi\HospitalBundle\Services\HmsService
          arguments: [@event_dispatcher]
          calls:
                - [ setContainer,[ @service_container ] ]
          tags:
              - { name: kernel.event_listener, event: pixi.admin_js_files, method: adminJsFiles }
              - { name: kernel.event_listener, event: pixi.admin_routes, method: adminRoutes }
              - { name: kernel.event_listener, event: pixi.admin_sidebar_entries, method: adminSidebar }